// Temporary function for testing
export const FETCH_RECORDS = "FETCH_RECORDS"

export const SET_TOKEN = "SET_TOKEN"

export const FETCH_PAYMENTS = "FETCH_PAYMENTS"
export const FETCH_SALARIES = "FETCH_SALARIES"
export const FETCH_FUNDS = "FETCH_FUNDS"
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS"
export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES"

export const FETCH_ACCOUNT_TREE = "FETCH_ACCOUNT_TREE"

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION"
export const CREATE_TRANSACTION = "CREATE_TRANSACTION"

